[book]
authors = ["ojn"]
language = "en"
description = "just my plain text notes"
src = "src"
title = "obvious jokes negated"

[output.html.search]
enable = false

[build]
build-dir = "docs"
create-missing = true
