#!/bin/bash

# tree to print files

tree=$(tree -tf --noreport -I '.*|img|dist|*.xml' --charset ascii $1 |
       sed -e 's/| \+/  /g' -e 's/[|`]-\+/ */g' -e 's:\(* \)\(\(.*/\)\([^/]\+\)\):\1[\4](\2):g')

printf "# Project files \n\n${tree}"
